// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: dashboard.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetDailySummary_FullMethodName               = "/services.DashboardService/GetDailySummary"
	DashboardService_GetMonthlySales_FullMethodName               = "/services.DashboardService/GetMonthlySales"
	DashboardService_GetMonthlyBookingAndCustomers_FullMethodName = "/services.DashboardService/GetMonthlyBookingAndCustomers"
	DashboardService_GetBestSellers_FullMethodName                = "/services.DashboardService/GetBestSellers"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	// RPC สำหรับดึงข้อมูลสรุปใน Dashboard
	GetDailySummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDailySummaryResponse, error)
	// RPC สำหรับดึงข้อมูลกราฟยอดขายรายเดือน/ปี
	GetMonthlySales(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlySalesResponse, error)
	// RPC สำหรับดึงข้อมูลกราฟยอดจองและจำนวนลูกค้ารายเดือน
	GetMonthlyBookingAndCustomers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlyBookingAndCustomersResponse, error)
	// RPC สำหรับดึงข้อมูลเมนูขายดี
	GetBestSellers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBestSellersResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetDailySummary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDailySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailySummaryResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDailySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetMonthlySales(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlySalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlySalesResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetMonthlySales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetMonthlyBookingAndCustomers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMonthlyBookingAndCustomersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyBookingAndCustomersResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetMonthlyBookingAndCustomers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetBestSellers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetBestSellersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBestSellersResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetBestSellers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	// RPC สำหรับดึงข้อมูลสรุปใน Dashboard
	GetDailySummary(context.Context, *emptypb.Empty) (*GetDailySummaryResponse, error)
	// RPC สำหรับดึงข้อมูลกราฟยอดขายรายเดือน/ปี
	GetMonthlySales(context.Context, *emptypb.Empty) (*GetMonthlySalesResponse, error)
	// RPC สำหรับดึงข้อมูลกราฟยอดจองและจำนวนลูกค้ารายเดือน
	GetMonthlyBookingAndCustomers(context.Context, *emptypb.Empty) (*GetMonthlyBookingAndCustomersResponse, error)
	// RPC สำหรับดึงข้อมูลเมนูขายดี
	GetBestSellers(context.Context, *emptypb.Empty) (*GetBestSellersResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetDailySummary(context.Context, *emptypb.Empty) (*GetDailySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailySummary not implemented")
}
func (UnimplementedDashboardServiceServer) GetMonthlySales(context.Context, *emptypb.Empty) (*GetMonthlySalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlySales not implemented")
}
func (UnimplementedDashboardServiceServer) GetMonthlyBookingAndCustomers(context.Context, *emptypb.Empty) (*GetMonthlyBookingAndCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyBookingAndCustomers not implemented")
}
func (UnimplementedDashboardServiceServer) GetBestSellers(context.Context, *emptypb.Empty) (*GetBestSellersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestSellers not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetDailySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDailySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDailySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDailySummary(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetMonthlySales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetMonthlySales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetMonthlySales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetMonthlySales(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetMonthlyBookingAndCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetMonthlyBookingAndCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetMonthlyBookingAndCustomers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetMonthlyBookingAndCustomers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetBestSellers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetBestSellers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetBestSellers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetBestSellers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailySummary",
			Handler:    _DashboardService_GetDailySummary_Handler,
		},
		{
			MethodName: "GetMonthlySales",
			Handler:    _DashboardService_GetMonthlySales_Handler,
		},
		{
			MethodName: "GetMonthlyBookingAndCustomers",
			Handler:    _DashboardService_GetMonthlyBookingAndCustomers_Handler,
		},
		{
			MethodName: "GetBestSellers",
			Handler:    _DashboardService_GetBestSellers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
