services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - .env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - .env:/app/.env
    networks:
      - my-network
    image: booking-service 
    container_name: booking-service 

networks:
  my-network:
    external: true 
